### PR TITLE
Updated scaling for splash hash in R package

### PR DESCRIPTION
**Pull request by sneumann**
Hi, passes test of 409 out of 410 hashes in the test set, still working on the last one.

### CODE REVIEW

**Comment by bhajunsingh** [comment]
On line 21, try changing

    peaks[,2] <- as.integer(peaks[,2] / max(peaks[,2]) * RELATIVE_INTENSITY_SCALE)

to

    peaks[,2] <- as.integer(peaks[,2] / max(peaks[,2]) * RELATIVE_INTENSITY_SCALE + EPS_CORRECTION)

**Comment by sneumann** [comment]
Excellent @bhajunsingh , that did it. Cleaning up now, ETA 2hrs.

**Comment by berlinguyinca** [comment]
Great! Glad it worked now.

**Comment by sneumann** [comment]
Ok, package cleaned up, renamed to splashR, passing all tests. I'd say we call it verified now :-)

**Pull request merged**
