### PR TITLE
First R package

### PR DESCRIPTION
**Pull request by egonw**
Example code (by Steffen):

    caffeine <- cbind(
      mz=c(138.0641, 195.0815),
      intensity=c(71.59, 261.7)
    )
    splash <- getSplash(caffeine)

### CODE REVIEW

**Comment by egonw** [comment]
Try with:

    > library(devtools)
    > install_github("egonw/spectra-hash@R-package", subdir="R")

**Comment by berlinguyinca** [comment]
Looks great,  I merged in a little bit.

G.

**Comment by berlinguyinca** [comment]
also how would you propose to process a real spectra, like from a File or String? Since they are mostly paired as mass:intensity, it might be awkward to convert them to vectors first

**Comment by egonw** [comment]
@berlinguyinca, would the mass:intensity's be space or comma separated?

**Comment by bhajunsingh** [comment]
@egonw We have been using space as a delimiter between ion:intensity pairs.

**Pull request merged**
